name: pr-test-runner

on:
  push:
    branches:
      - main
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: npm install 
      - run: npm install cypress@10.9.0 --save-dev
      - run: npx cypress --version
      - run: npm install @percy/cli
      - run: npx percy exec -- cypress run
        env:
          PERCY_TOKEN: ${{ secrets.percy_token }}
