name: pr-test-runner

on:
  push:
    branches:
      - main
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
         build: npm install cypress@10.9.0 @percy/cli --save-dev
         command-prefix: npx percy exec -- cypress run
        env:
          PERCY_TOKEN: $
