name: pr-test-runner

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm install cypress@10.9.0 --save-dev
      - run: npm install --save-dev @percy/cli
      - run: npx percy exec -- cypress run
        env:
          PERCY_TOKEN: $
